[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixos-22.05.tar.gz"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
